-- Creación del usuario TRONUSER y asignación de privilegios básicos
    CREATE USER TRONUSER IDENTIFIED BY w;
    GRANT CONNECT TO TRONUSER;

-- Tabla DatabaseLogStructure y grants asociados
    CREATE TABLE DatabaseLogStructure(
        text VARCHAR2(255) NOT NULL,
        isMalicious NUMBER(1) CHECK (isMalicious BETWEEN 0 AND 1) NOT NULL, -- 1 PARA SÍ, 0 PARA NO
        feedback VARCHAR2(255) NOT NULL
    );
    GRANT SELECT ON DatabaseLogStructure TO TRONUSER;

-- Tabla FirewallLogStructure y grants asociados
    CREATE TABLE FirewallLogStructure(
        text VARCHAR2(255) NOT NULL,
        isPermitted NUMBER(1) CHECK (isPermitted BETWEEN 0 AND 1) NOT NULL, -- 1 PARA SÍ, 0 PARA NO
        feedback VARCHAR2(255) NOT NULL
    );
    GRANT SELECT ON FirewallLogStructure TO TRONUSER;

-- Tabla Roles y grants asociados
    CREATE TABLE Roles( 
        role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role_name VARCHAR2(50) NOT NULL UNIQUE
    );
    GRANT SELECT ON Roles TO TRONUSER;

-- Inserción inicial de roles
    INSERT INTO Roles (role_name) VALUES ('player');
    INSERT INTO Roles (role_name) VALUES ('admin');

-- Tabla Users y grants asociados
    CREATE TABLE Users(
        user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(50) NOT NULL,
        role_id NUMBER DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES Roles(role_id)
    );
    GRANT SELECT, INSERT ON Users TO TRONUSER;

-- Vista para ver los usuarios y sus roles y grants asociados
    CREATE OR REPLACE VIEW viewUsers AS
        SELECT u.user_id, u.username, r.role_name, u.created_at
        FROM Users u
        JOIN Roles r ON u.role_id = r.role_id;
    GRANT SELECT ON viewUsers TO TRONUSER;

-- Procedimiento para insertar User y grants asociados
    CREATE OR REPLACE PROCEDURE procedInsertUser(
        p_username IN VARCHAR2,
        p_role_id IN NUMBER DEFAULT 1
    ) AS
    BEGIN
        INSERT INTO Users (username, role_id) VALUES (p_username, p_role_id);
    END;
    /
    GRANT EXECUTE ON procedInsertUser TO TRONUSER;

-- Tabla MatchesHistory y grants asociados
    CREATE TABLE MatchesHistory(
        match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER,
        username VARCHAR2(50) NOT NULL,
        time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        score NUMBER,
        result VARCHAR2(20),
        CONSTRAINT fk_match_user FOREIGN KEY (user_id) REFERENCES Users(user_id)
    );
    GRANT SELECT, INSERT ON MatchesHistory TO TRONUSER;

-- Vista para ver el historial de partidas (MatchesHistory) de los jugadores y grants asociados
    CREATE OR REPLACE VIEW viewMatchesHistory AS
        SELECT * FROM MatchesHistory;
    GRANT SELECT ON viewMatchesHistory TO TRONUSER;

-- Procedimiento para insertar MatchesHistory y grants asociados
    CREATE OR REPLACE PROCEDURE procedInsertMatchHistory(
        p_user_id IN NUMBER,
        p_username IN VARCHAR2,
        p_time IN TIMESTAMP,
        p_score IN NUMBER,
        p_result IN VARCHAR2
    ) AS
    BEGIN
        INSERT INTO MatchesHistory (user_id, username, time, score, result) 
        VALUES (p_user_id, p_username, p_time, p_score, p_result);
    END;
    /
    GRANT EXECUTE ON procedInsertMatchHistory TO TRONUSER;

-- Tabla completa Feedback y grants asociados
    -- Tabla anidada feedback_nt
        CREATE OR REPLACE TYPE feedback_t AS OBJECT(feedback VARCHAR2(255));
        CREATE OR REPLACE TYPE feedback_nt AS TABLE OF feedback_t;
    CREATE TABLE Feedback(
        feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
        feedback feedback_nt,
        CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES Users(user_id)
    ) NESTED TABLE feedback STORE AS feedback_nt_tab;
    GRANT SELECT, INSERT ON Feedback TO TRONUSER;
-- Procedimiento para insertar Feedback y grants asociados
    CREATE OR REPLACE PROCEDURE procedInsertFeedback(
        p_user_id IN NUMBER,
        p_rating IN NUMBER,
        p_feedback IN feedback_nt
    ) AS
    BEGIN
        INSERT INTO Feedback (user_id, rating, feedback) 
        VALUES (p_user_id, p_rating, p_feedback);
    END;
    /
    GRANT EXECUTE ON procedInsertFeedback TO TRONUSER;

-- Vista para ver los feedbacks y grants asociados
    CREATE OR REPLACE VIEW viewFeedback AS
    SELECT f.feedback_id, f.user_id, u.username, f.rating, fb.feedback
    FROM Feedback f 
    JOIN Users u ON f.user_id = u.user_id
    JOIN TABLE (f.feedback) fb ON 1=1;
    GRANT SELECT ON viewFeedback TO TRONUSER;

-- Vista para ver el último feedback del usuario activo y grants asociados
    CREATE OR REPLACE VIEW viewLastFeedback AS
    SELECT *
    FROM (
        SELECT f.feedback_id, u.username, f.rating, f.feedback, 
               ROW_NUMBER() OVER (PARTITION BY f.user_id ORDER BY f.feedback_id DESC) AS rn
        FROM Feedback f
        JOIN Users u ON f.user_id = u.user_id
    ) 
    WHERE rn = 1;
    GRANT SELECT ON viewLastFeedback TO TRONUSER;

-- Procedimiento para ejecutar alguna de las vistas
    CREATE OR REPLACE PROCEDURE procedExecuteView(
        p_view_name IN VARCHAR2
    ) AS
        v_sql VARCHAR2(1000);
    BEGIN
        v_sql := 'SELECT * FROM ' || p_view_name;
        EXECUTE IMMEDIATE v_sql;
    END;
    /
    GRANT EXECUTE ON procedExecuteView TO TRONUSER;

-- Procedimiento para contar registros en una tabla
    CREATE OR REPLACE PROCEDURE procedCountRecords(
        p_table_name IN VARCHAR2,
        p_count OUT INT
    ) AS
        v_sql VARCHAR2(1000);
    BEGIN
        v_sql := 'SELECT COUNT(*) FROM ' || p_table_name;
        EXECUTE IMMEDIATE v_sql INTO p_count;
    END;
    /
    GRANT EXECUTE ON procedCountRecords TO TRONUSER;

PURGE RECYCLEBIN;